spring:
  datasource:

    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/o3o
    username: sa
    password: 123456
    schema: classpath:schema.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2

